### ISSUE TITLE
Error in request. 

### ISSUE THREAD

**Issue by shlokspeare** [pdincau/gcm-erlang#17]
Error in request. Reason was: Bad Request - "\"registration_ids\" field is not a JSON array\n"

when trying to execute: gcm:push(foo,<<"APA91bEoSpQaIob__________S3IgPfk3-ZjwODp4b">>,[{<<"data">>, [{<<"message">>, <<"a message">>}]}]). 

unable to understand the significance of registered name

**Comment by pdincau** [comment]
You are passing the registration id as a single binary while it should be a list of binaries. This is showed in readme.
