### ISSUE TITLE
Retry doesn't work

### ISSUE THREAD

**Issue by guero235** [pdincau/gcm-erlang#18]
in the "do_backoff" function to make this work

```erlang
timer:apply_after(RetryAfter * 1000, ?MODULE, do_push, [RegIds, Message, Key, Retry - 1])
```

i had to export the "do_push" function.

**Comment by pdincau** [comment]
@guero235 correct, function must be exported. 

This sucks...do you mind open a PR while i think on how to solve this in a better way?

**Comment by guero235** [comment]
I may have some time later to do a proper PR, but here's a way to fix it without exporting the "do_push"

```erlang
 timer:apply_after(RetryAfter * 1000, ?MODULE, push, [self(), RegIds, Message, Retry - 1])
```

Since the gen_server already has the "Key" variable, we don't need to send it back to itself, and the module is already exporting a push/4 taking in a "Name"

**Comment by pdincau** [comment]
@guero235 thanks! i will fix this next week!

**Comment by pdincau** [comment]
closed! Thank you very much @guero235
