### ISSUE TITLE
What is the payload if one has to use gcm for pushing data to apple devices

### ISSUE THREAD

**Issue by shlokspeare** [pdincau/gcm-erlang#21]
{
  "to" : "REGISTRATION_TOKEN",
   "notification" : {
    "sound" : "default",
    "badge" : "1",
    "title" : "default",
    "body"  : "Test",
  },
  "content_available" : true,
  "priority" : "normal",
}

**Comment by shlokspeare** [comment]
Tried with this after starting gcm:start(foo, "SERVER_KEY").
gcm:push(foo, [<<"PUSH_TOKEN">>],
    [{<<"data">>,
        [{<<"priority">>,<<"high">>},
        {<<"content_available">>, true},
        {<<"notification">>,
            [{<<"sound">>,<<"default">>},
            {<<"badge">>, <<"1">>},
            {<<"body">>,<<"OYEOK bot">>},
            {<<"title">>,<<"default">>}]}]}]).

**Comment by pdincau** [comment]
i have never tried to push to apns using gcm. For apple I know [ex_apn ](https://github.com/l4u/ex_apns) which works pretty well.
